<?php
spl_autoload_register(function ($class)
{include"classes/".$class.".php";});
//check of the user is logged in:
$session = new UserSessionHandler();
$session->confirm_logged_in()
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Midnight Scream Spectacle - Booking</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Creepster&family=EB+Garamond:wght@400;700&display=swap');
        body {
            font-family: 'EB Garamond', serif;
            background-color: #0f0a1a;
            color: #e0d6eb;
        }
        .horror-font {
            font-family: 'Creepster', cursive;
        }
        .purple-dark {
            background-color: #1a1029;
        }
        .purple-light {
            background-color: #2a1a4a;
        }
        .moss-green {
            background-color: #1a2910;
        }
        .blood-red {
            color: #ff3a3a;
        }
        .glow {
            text-shadow: 0 0 5px #9b59b6, 0 0 10px #9b59b6;
        }
        .seat {
            width: 40px;
            height: 40px;
            margin: 5px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            border-radius: 4px;
            transition: all 0.2s;
        }
        .seat:hover:not(.occupied) {
            transform: scale(1.1);
        }
        .seat.selected {
            background-color: #9b59b6 !important;
        }
        .seat.occupied {
            background-color: #ff3a3a;
            cursor: not-allowed;
        }
        .screen {
            background: linear-gradient(to bottom, rgba(255,255,255,0.1), rgba(255,255,255,0.3));
            height: 30px;
            width: 100%;
            margin: 30px 0;
            transform: perspective(400px) rotateX(-20deg);
            box-shadow: 0 3px 10px rgba(255,255,255,0.7);
        }
        .checkout-btn:disabled {
            opacity: 0.5;
            cursor: not-allowed;
        }
    </style>
</head>
<body class="min-h-screen">
<!-- Navigation -->
<nav class="purple-dark sticky top-0 z-50 shadow-lg">
    <div class="container mx-auto px-6 py-3">
        <div class="flex items-center justify-between">
            <div class="flex items-center space-x-8">
                <a href="index.php" class="flex items-center">
                    <span class="horror-font text-3xl blood-red glow">Midnight Scream</span>
                </a>
            </div>
            <div class="hidden md:flex items-center space-x-8">
                <a href="index.php" class="text-white hover:text-purple-300">Home</a>
                <a href="movies.php" class="text-white hover:text-purple-300">Movies</a>
                <a href="about.php" class="text-white hover:text-purple-300">About Us</a>
                <a href="login.php" class="text-white hover:text-purple-300">Login</a>
            </div>
            <div class="md:hidden">
                <button class="text-white focus:outline-none">
                    <i data-feather="menu"></i>
                </button>
            </div>
        </div>
    </div>
</nav>

<!-- Booking Section -->
<section class="py-16">
    <div class="container mx-auto px-6 max-w-4xl">
        <div class="purple-dark rounded-lg shadow-xl overflow-hidden mb-8">
            <div class="p-6">
                <h2 class="horror-font text-3xl blood-red mb-2">The Exorcist</h2>
                <div class="flex flex-wrap gap-4 mb-4">
                    <span class="flex items-center"><i data-feather="calendar" class="mr-2"></i> Friday, October 13</span>
                    <span class="flex items-center"><i data-feather="clock" class="mr-2"></i> 19:00</span>
                    <span class="flex items-center"><i data-feather="tv" class="mr-2"></i> Hall A</span>
                </div>
            </div>
        </div>

        <!-- Screen and Seats -->
        <div class="text-center mb-12">
            <div class="screen"></div>

            <div id="seats-container" class="mb-8">
                <!-- Seats will be generated by JavaScript -->
            </div>

            <div class="flex justify-center gap-8 mb-8">
                <div class="flex items-center">
                    <div class="seat bg-gray-600 mr-2"></div>
                    <span>Available</span>
                </div>
                <div class="flex items-center">
                    <div class="seat selected mr-2"></div>
                    <span>Selected</span>
                </div>
                <div class="flex items-center">
                    <div class="seat occupied mr-2"></div>
                    <span>Occupied</span>
                </div>
            </div>
        </div>

        <!-- Booking Summary -->
        <div class="purple-dark rounded-lg shadow-xl p-6">
            <h3 class="horror-font text-2xl blood-red mb-4">Your Order</h3>
            <div class="flex justify-between mb-4">
                <span>Tickets (<span id="selected-count">0</span>):</span>
                <span>$<span id="total-price">0.00</span></span>
            </div>
            <div class="flex justify-between mb-6">
                <span>Service Fee:</span>
                <span>$2.50</span>
            </div>
            <div class="flex justify-between font-bold text-lg mb-6">
                <span>Total:</span>
                <span>$<span id="grand-total">2.50</span></span>
            </div>
            <button id="checkout-btn" class="w-full moss-green hover:bg-green-900 text-white font-bold py-3 px-6 rounded transition duration-300 checkout-btn" disabled>
                Proceed to Checkout
            </button>
        </div>
    </div>
</section>

<!-- Footer -->
<footer class="purple-dark py-8">
    <div class="container mx-auto px-6">
        <div class="flex flex-col md:flex-row justify-between items-center">
            <div class="mb-4 md:mb-0">
                <span class="horror-font text-2xl blood-red">Midnight Scream</span>
                <p class="text-sm mt-1">© 2023 All Rights Reserved</p>
            </div>
            <div class="flex flex-col md:flex-row md:space-x-8 space-y-2 md:space-y-0 text-sm">
                <a href="#" class="hover:text-purple-300">Privacy Policy</a>
                <a href="#" class="hover:text-purple-300">Terms of Service</a>
                <a href="#" class="hover:text-purple-300">Contact Us</a>
                <a href="admin/login.php" class="hover:text-purple-300">Admin</a>
            </div>
        </div>
    </div>
</footer>

<script>
    feather.replace();
    // Seat booking logic
    document.addEventListener('DOMContentLoaded', function() {
        const container = document.getElementById('seats-container');
        const seatCount = document.getElementById('selected-count');
        const totalPrice = document.getElementById('total-price');
        const grandTotal = document.getElementById('grand-total');
        const checkoutBtn = document.getElementById('checkout-btn');

        const rows = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];
        const cols = 10;
        const seatPrice = 12.50;
        const serviceFee = 2.50;

        let selectedSeats = [];

        // Generate seats
        rows.forEach(row => {
            const rowDiv = document.createElement('div');
            rowDiv.className = 'mb-4';

            for (let i = 1; i <= cols; i++) {
                const seat = document.createElement('div');
                seat.className = 'seat bg-gray-600';
                seat.dataset.id = `${row}${i}`;

                // Randomly occupy some seats (20% chance)
                if (Math.random() < 0.2) {
                    seat.classList.add('occupied');
                }

                seat.addEventListener('click', () => toggleSeat(seat));
                rowDiv.appendChild(seat);
            }

            container.appendChild(rowDiv);
        });

        function toggleSeat(seat) {
            // Don't allow selection of occupied seats
            if (seat.classList.contains('occupied')) return;

            const seatId = seat.dataset.id;
            const index = selectedSeats.indexOf(seatId);

            if (index === -1) {
                // Check if new selection is adjacent to existing selections (if any)
                if (selectedSeats.length > 0) {
                    const lastSeat = selectedSeats[selectedSeats.length - 1];
                    const lastRow = lastSeat.charAt(0);
                    const lastNum = parseInt(lastSeat.substring(1));

                    const currentRow = seatId.charAt(0);
                    const currentNum = parseInt(seatId.substring(1));

                    // Same row and consecutive number
                    if (currentRow === lastRow && Math.abs(currentNum - lastNum) === 1) {
                        selectedSeats.push(seatId);
                        seat.classList.add('selected');
                    } else {
                        alert('Please select adjacent seats without gaps');
                        return;
                    }
                } else {
                    // First selection
                    selectedSeats.push(seatId);
                    seat.classList.add('selected');
                }
            } else {
                // Deselect seat
                selectedSeats.splice(index, 1);
                seat.classList.remove('selected');
            }

            updateSelection();
        }

        function updateSelection() {
            const count = selectedSeats.length;
            const subtotal = count * seatPrice;
            const total = subtotal + serviceFee;

            seatCount.textContent = count;
            totalPrice.textContent = subtotal.toFixed(2);
            grandTotal.textContent = total.toFixed(2);

            checkoutBtn.disabled = count === 0;
        }

        checkoutBtn.addEventListener('click', () => {
            // In a real app, this would redirect to payment processor
            alert(`Redirecting to payment for ${selectedSeats.length} ticket(s). Total: $${(selectedSeats.length * seatPrice + serviceFee).toFixed(2)}`);
            // window.location.href = 'payment.php';
        });
    });
</script>
</body>
</html>
